version: '3.8'
services:
  express:
    container_name: express
    image: 'node:20'
    ports:
      - "8080:8080"
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    environment:
      - NODE_ENV=development
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm start

  react:
    container_name: react
    image: 'node:20'
    ports:
      - "80:3000"
    volumes:
      - ./front:/app
    depends_on:
      - express
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run dev